version: '3'

services:
  api-web:
    build: .
    image: dollarstocents:latest
    container_name: api-dollarstocents
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    network_mode: bridge
    restart: always
    command: npm start
    